name: password_entropy
description: This package aims to calculate entrophy for plain text passwords, different implementations may have slighty different results from this package.
version: 2.0.0
repository: https://github.com/ThiagoFontes/dart_packages/tree/main/password_entropy

environment:
  sdk: ^3.0.3

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
