name: password_entropy
description: A passoword entrophy calculation package.
version: 1.0.0
repository: https://github.com/ThiagoFontes/dart_packages/tree/main/password_entropy

environment:
  sdk: ^3.0.3

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
